### ISSUE TITLE
Arrow icon not disappearing

### ISSUE THREAD

**Issue by dgdsouza** [areasflavio/react-native-onboarding-screens#1]
The arrow icon stays visible on the last screen:
<img width="193" alt="image" src="https://github.com/user-attachments/assets/33cdad37-7a5f-47ea-be70-d66efd4e1ef7">

**Comment by dgdsouza** [comment]
This is a bug in reanimate:
https://github.com/software-mansion/react-native-reanimated/issues/5677

**Comment by imrtls00** [comment]
Bump: Same issue.
Has anyone found a fix? @here

**Comment by areasflavio** [comment]
Thanks @deelo55 and @imrtls00

**Comment by imrtls00** [comment]
Thanks @areasflavio , keep creating 🎉 

I saw your solution, I fixed the Button component similarly: https://github.com/imrtls00/ProjectEVO-Expo/blob/main/src/components/OnboardingButton.tsx
